server:
  port: 7072

## Dubbo 服务提供者配置
#应用名
spring:
  dubbo:
    application:
      name: provider2
    #zookeeper的注册地址
    registry:
      address: zookeeper://127.0.0.1:2181
    #注册zookeeper的协议
    protocol:
      name: dubbo
      #提供者注册到zookeeper上的端口号
      port: 20882
    #提供服务的业务层
    scan: com.java.zd.provider.service.impl
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///k9503?useSSL=false
    username: root
    password: Root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

#配置pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启MyBatis的二级缓存
    cache-enabled: true
  type-aliases-package: com.java.zd.commons.entity
